[package]
name = "nillion-technical"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.4"
prost = "0.12.3"
rand = "0.8.5"
tonic = "0.10.2"

[build-dependencies]
tonic-build = "0.10"
